// Source: 2026-27 ACT Budget Cost of Living Statement, Table 3.3.2
// Extracted at the workshop. Every figure traces to one row of that table.
window.HOUSEHOLDS = [
 {
  "id": "1",
  "suburb": "Belconnen",
  "household": "Single, pensioner, in own unit, no car",
  "years": {
   "2025-26": {
    "id": "1",
    "suburb": "Belconnen",
    "household": "Single, pensioner, in own unit, no car",
    "year": "2025-26",
    "disposable_income": 29900.0,
    "rates_pfesl_sfl_hl": 1801.0,
    "conveyance_duty": 0.0,
    "vehicle_charges": 0.0,
    "public_transport_fares": 1411.0,
    "utilities": 4248.0,
    "rates_pfesl_concession": 865.0,
    "conveyance_duty_concession": 0.0,
    "vehicle_concession": 0.0,
    "public_transport_concession": 706.0,
    "utilities_concession": 800.0,
    "net_disposable_income": 24811.0,
    "change": null
   },
   "2026-27": {
    "id": "1",
    "suburb": "Belconnen",
    "household": "Single, pensioner, in own unit, no car",
    "year": "2026-27",
    "disposable_income": 31200.0,
    "rates_pfesl_sfl_hl": 1739.0,
    "conveyance_duty": 0.0,
    "vehicle_charges": 0.0,
    "public_transport_fares": 1665.0,
    "utilities": 4570.0,
    "rates_pfesl_concession": 883.0,
    "conveyance_duty_concession": 0.0,
    "vehicle_concession": 0.0,
    "public_transport_concession": 835.0,
    "utilities_concession": 800.0,
    "net_disposable_income": 25744.0,
    "change": 933.0
   }
  }
 },
 {
  "id": "2",
  "suburb": "Braddon",
  "household": "Couple, pensioners, in own house, 2 cars, downsizing to unit in 2026-27",
  "years": {
   "2025-26": {
    "id": "2",
    "suburb": "Braddon",
    "household": "Couple, pensioners, in own house, 2 cars, downsizing to unit in 2026-27",
    "year": "2025-26",
    "disposable_income": 45000.0,
    "rates_pfesl_sfl_hl": 6493.0,
    "conveyance_duty": 0.0,
    "vehicle_charges": 1434.0,
    "public_transport_fares": 0.0,
    "utilities": 6125.0,
    "rates_pfesl_concession": 865.0,
    "conveyance_duty_concession": 0.0,
    "vehicle_concession": 1114.0,
    "public_transport_concession": 0.0,
    "utilities_concession": 800.0,
    "net_disposable_income": 33727.0,
    "change": null
   },
   "2026-27": {
    "id": "2",
    "suburb": "Braddon",
    "household": "Couple, pensioners, in own house, 2 cars, downsizing to unit in 2026-27",
    "year": "2026-27",
    "disposable_income": 47100.0,
    "rates_pfesl_sfl_hl": 2208.0,
    "conveyance_duty": 10568.0,
    "vehicle_charges": 1540.0,
    "public_transport_fares": 0.0,
    "utilities": 6510.0,
    "rates_pfesl_concession": 883.0,
    "conveyance_duty_concession": 10568.0,
    "vehicle_concession": 1217.0,
    "public_transport_concession": 0.0,
    "utilities_concession": 800.0,
    "net_disposable_income": 39742.0,
    "change": 6015.0
   }
  }
 },
 {
  "id": "3",
  "suburb": "Banks",
  "household": "Single parent, first income quintile, in own house, 1 car, 1\u00a0child who catches the bus to school",
  "years": {
   "2025-26": {
    "id": "3",
    "suburb": "Banks",
    "household": "Single parent, first income quintile, in own house, 1 car, 1\u00a0child who catches the bus to school",
    "year": "2025-26",
    "disposable_income": 35800.0,
    "rates_pfesl_sfl_hl": 2953.0,
    "conveyance_duty": 0.0,
    "vehicle_charges": 717.0,
    "public_transport_fares": 937.0,
    "utilities": 6125.0,
    "rates_pfesl_concession": 0.0,
    "conveyance_duty_concession": 0.0,
    "vehicle_concession": 505.0,
    "public_transport_concession": 468.0,
    "utilities_concession": 800.0,
    "net_disposable_income": 26841.0,
    "change": null
   },
   "2026-27": {
    "id": "3",
    "suburb": "Banks",
    "household": "Single parent, first income quintile, in own house, 1 car, 1\u00a0child who catches the bus to school",
    "year": "2026-27",
    "disposable_income": 37000.0,
    "rates_pfesl_sfl_hl": 3022.0,
    "conveyance_duty": 0.0,
    "vehicle_charges": 770.0,
    "public_transport_fares": 1084.0,
    "utilities": 6510.0,
    "rates_pfesl_concession": 0.0,
    "conveyance_duty_concession": 0.0,
    "vehicle_concession": 555.0,
    "public_transport_concession": 542.0,
    "utilities_concession": 800.0,
    "net_disposable_income": 27511.0,
    "change": 670.0
   }
  }
 },
 {
  "id": "4",
  "suburb": "Cook",
  "household": "Single, fixed income retiree, in own house, 1 car",
  "years": {
   "2025-26": {
    "id": "4",
    "suburb": "Cook",
    "household": "Single, fixed income retiree, in own house, 1 car",
    "year": "2025-26",
    "disposable_income": 65300.0,
    "rates_pfesl_sfl_hl": 4990.0,
    "conveyance_duty": 0.0,
    "vehicle_charges": 717.0,
    "public_transport_fares": 0.0,
    "utilities": 4248.0,
    "rates_pfesl_concession": 0.0,
    "conveyance_duty_concession": 0.0,
    "vehicle_concession": 56.0,
    "public_transport_concession": 0.0,
    "utilities_concession": 0.0,
    "net_disposable_income": 56300.0,
    "change": null
   },
   "2026-27": {
    "id": "4",
    "suburb": "Cook",
    "household": "Single, fixed income retiree, in own house, 1 car",
    "year": "2026-27",
    "disposable_income": 68100.0,
    "rates_pfesl_sfl_hl": 4309.0,
    "conveyance_duty": 0.0,
    "vehicle_charges": 770.0,
    "public_transport_fares": 0.0,
    "utilities": 4573.0,
    "rates_pfesl_concession": 0.0,
    "conveyance_duty_concession": 0.0,
    "vehicle_concession": 61.0,
    "public_transport_concession": 0.0,
    "utilities_concession": 0.0,
    "net_disposable_income": 58509.0,
    "change": 2208.0
   }
  }
 },
 {
  "id": "5",
  "suburb": "Kingston",
  "household": "Single, second income quintile, in own unit, no car",
  "years": {
   "2025-26": {
    "id": "5",
    "suburb": "Kingston",
    "household": "Single, second income quintile, in own unit, no car",
    "year": "2025-26",
    "disposable_income": 61200.0,
    "rates_pfesl_sfl_hl": 2643.0,
    "conveyance_duty": 0.0,
    "vehicle_charges": 0.0,
    "public_transport_fares": 1411.0,
    "utilities": 4248.0,
    "rates_pfesl_concession": 0.0,
    "conveyance_duty_concession": 0.0,
    "vehicle_concession": 0.0,
    "public_transport_concession": 0.0,
    "utilities_concession": 0.0,
    "net_disposable_income": 52898.0,
    "change": null
   },
   "2026-27": {
    "id": "5",
    "suburb": "Kingston",
    "household": "Single, second income quintile, in own unit, no car",
    "year": "2026-27",
    "disposable_income": 63200.0,
    "rates_pfesl_sfl_hl": 2758.0,
    "conveyance_duty": 0.0,
    "vehicle_charges": 0.0,
    "public_transport_fares": 1665.0,
    "utilities": 4573.0,
    "rates_pfesl_concession": 0.0,
    "conveyance_duty_concession": 0.0,
    "vehicle_concession": 0.0,
    "public_transport_concession": 0.0,
    "utilities_concession": 0.0,
    "net_disposable_income": 54204.0,
    "change": 1306.0
   }
  }
 },
 {
  "id": "6",
  "suburb": "Turner",
  "household": "Single, third income quintile, 1 car, purchasing first unit in 2026-27",
  "years": {
   "2025-26": {
    "id": "6",
    "suburb": "Turner",
    "household": "Single, third income quintile, 1 car, purchasing first unit in 2026-27",
    "year": "2025-26",
    "disposable_income": 81600.0,
    "rates_pfesl_sfl_hl": 0.0,
    "conveyance_duty": 0.0,
    "vehicle_charges": 717.0,
    "public_transport_fares": 0.0,
    "utilities": 4248.0,
    "rates_pfesl_concession": 0.0,
    "conveyance_duty_concession": 0.0,
    "vehicle_concession": 0.0,
    "public_transport_concession": 0.0,
    "utilities_concession": 0.0,
    "net_disposable_income": 76635.0,
    "change": null
   },
   "2026-27": {
    "id": "6",
    "suburb": "Turner",
    "household": "Single, third income quintile, 1 car, purchasing first unit in 2026-27",
    "year": "2026-27",
    "disposable_income": 84200.0,
    "rates_pfesl_sfl_hl": 2559.0,
    "conveyance_duty": 14456.0,
    "vehicle_charges": 770.0,
    "public_transport_fares": 0.0,
    "utilities": 4573.0,
    "rates_pfesl_concession": 0.0,
    "conveyance_duty_concession": 14456.0,
    "vehicle_concession": 0.0,
    "public_transport_concession": 0.0,
    "utilities_concession": 0.0,
    "net_disposable_income": 76298.0,
    "change": -337.0
   }
  }
 },
 {
  "id": "7",
  "suburb": "Wright",
  "household": "Couple, third income quintile, 2 cars, first time buying house in 2026-27, 1 child who catches bus to school",
  "years": {
   "2025-26": {
    "id": "7",
    "suburb": "Wright",
    "household": "Couple, third income quintile, 2 cars, first time buying house in 2026-27, 1 child who catches bus to school",
    "year": "2025-26",
    "disposable_income": 163100.0,
    "rates_pfesl_sfl_hl": 0.0,
    "conveyance_duty": 0.0,
    "vehicle_charges": 1434.0,
    "public_transport_fares": 937.0,
    "utilities": 6125.0,
    "rates_pfesl_concession": 0.0,
    "conveyance_duty_concession": 0.0,
    "vehicle_concession": 0.0,
    "public_transport_concession": 468.0,
    "utilities_concession": 0.0,
    "net_disposable_income": 155072.0,
    "change": null
   },
   "2026-27": {
    "id": "7",
    "suburb": "Wright",
    "household": "Couple, third income quintile, 2 cars, first time buying house in 2026-27, 1 child who catches bus to school",
    "year": "2026-27",
    "disposable_income": 168400.0,
    "rates_pfesl_sfl_hl": 4061.0,
    "conveyance_duty": 48358.0,
    "vehicle_charges": 1540.0,
    "public_transport_fares": 1084.0,
    "utilities": 6510.0,
    "rates_pfesl_concession": 0.0,
    "conveyance_duty_concession": 48358.0,
    "vehicle_concession": 0.0,
    "public_transport_concession": 542.0,
    "utilities_concession": 0.0,
    "net_disposable_income": 155747.0,
    "change": 675.0
   }
  }
 },
 {
  "id": "8",
  "suburb": "Ainslie",
  "household": "Couple, fourth income quintile, in own house, 2 cars, 1 school child and 1 tertiary student who catch the bus",
  "years": {
   "2025-26": {
    "id": "8",
    "suburb": "Ainslie",
    "household": "Couple, fourth income quintile, in own house, 2 cars, 1 school child and 1 tertiary student who catch the bus",
    "year": "2025-26",
    "disposable_income": 210100.0,
    "rates_pfesl_sfl_hl": 6144.0,
    "conveyance_duty": 0.0,
    "vehicle_charges": 1434.0,
    "public_transport_fares": 2298.0,
    "utilities": 7981.0,
    "rates_pfesl_concession": 0.0,
    "conveyance_duty_concession": 0.0,
    "vehicle_concession": 0.0,
    "public_transport_concession": 1149.0,
    "utilities_concession": 0.0,
    "net_disposable_income": 193392.0,
    "change": null
   },
   "2026-27": {
    "id": "8",
    "suburb": "Ainslie",
    "household": "Couple, fourth income quintile, in own house, 2 cars, 1 school child and 1 tertiary student who catch the bus",
    "year": "2026-27",
    "disposable_income": 217000.0,
    "rates_pfesl_sfl_hl": 6642.0,
    "conveyance_duty": 0.0,
    "vehicle_charges": 1540.0,
    "public_transport_fares": 2337.0,
    "utilities": 8429.0,
    "rates_pfesl_concession": 0.0,
    "conveyance_duty_concession": 0.0,
    "vehicle_concession": 0.0,
    "public_transport_concession": 1168.0,
    "utilities_concession": 0.0,
    "net_disposable_income": 199220.0,
    "change": 5828.0
   }
  }
 },
 {
  "id": "9",
  "suburb": "Forrest",
  "household": "Couple, fifth income quintile, in own house, 2 cars, 2 children who catch the bus to school",
  "years": {
   "2025-26": {
    "id": "9",
    "suburb": "Forrest",
    "household": "Couple, fifth income quintile, in own house, 2 cars, 2 children who catch the bus to school",
    "year": "2025-26",
    "disposable_income": 311900.0,
    "rates_pfesl_sfl_hl": 15789.0,
    "conveyance_duty": 0.0,
    "vehicle_charges": 1434.0,
    "public_transport_fares": 1874.0,
    "utilities": 7981.0,
    "rates_pfesl_concession": 0.0,
    "conveyance_duty_concession": 0.0,
    "vehicle_concession": 0.0,
    "public_transport_concession": 937.0,
    "utilities_concession": 0.0,
    "net_disposable_income": 285759.0,
    "change": null
   },
   "2026-27": {
    "id": "9",
    "suburb": "Forrest",
    "household": "Couple, fifth income quintile, in own house, 2 cars, 2 children who catch the bus to school",
    "year": "2026-27",
    "disposable_income": 322000.0,
    "rates_pfesl_sfl_hl": 17872.0,
    "conveyance_duty": 0.0,
    "vehicle_charges": 1540.0,
    "public_transport_fares": 2168.0,
    "utilities": 8429.0,
    "rates_pfesl_concession": 0.0,
    "conveyance_duty_concession": 0.0,
    "vehicle_concession": 0.0,
    "public_transport_concession": 1084.0,
    "utilities_concession": 0.0,
    "net_disposable_income": 293075.0,
    "change": 7316.0
   }
  }
 }
];
